services:
  - type: web
    name: portofolio-belva
    env: php
    plan: free
    buildCommand: "composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache"
    startCommand: "vendor/bin/heroku-php-apache2 public/"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr