services:
  - type: web
    name: portofolio-belva
    env: docker
    plan: free
    repo: https://github.com/leandrabelva/portofolio-leandrabelva
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
        
databases:
  - name: portofolio_belva_db
    databaseName: portofolio_belva
    user: portofolio_user
    plan: free